apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-{{.projectname}}-service-account
  namespace: {{.projectname}}

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-{{.projectname}}-service-account-binding
subjects:
  - kind: ServiceAccount
    name: kubernetes-{{.projectname}}-service-account
    namespace: {{.projectname}}
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: ""
